nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: false
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Custom-Auth', 'AUTH_TOKEN']
        expose_headers: ['Link']
        hosts: []
        max_age: 3600
        forced_allow_origin_value: ~

    paths:
        '^/api/':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth', 'AUTH_TOKEN']
                allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
                max_age: 3600
        '^/': null
