dashboard:
    path: /admin
    controller: App\Controller\AdminController::index

api_login_check:
    path: /api/login_check


gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh


